appName: currencyservice
appImage: docker.io/c0dysharma/currencyservice
appVersion: 2
appReplicas: 2
containerPort: 7000
containerEnvVars: 
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7000